Add missing dependency to google_platform build
This issue is 100% reproducible with --jobs=1 build.

When (target) google_platform is built, cmds/Makefile actually
builds both the target version and host version of each binary.

I'm not convinced that it is the right thing to do, but to fix
the build error, target google_platform needs to depend on
host-libcurl.

finaltargets.google_platform-HEAD: .../out/host/usr/bin/ccache
.../out/host/usr/bin/ccache /usr/bin/gcc -Wall -Wextra -Wswitch-enum
-Werror -Wno-unused-parameter -g -O -std=c99 -D_GNU_SOURCE  -pipe -O2
-g2 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64
-I.../out/host/usr/mipsel-unknown-linux-uclibc/sysroot/usr/include/python2.7
-I.../out/host/usr/mipsel-unknown-linux-uclibc/sysroot/usr/include/libnl3
-I.../out/build/backports-custom-HEAD/include/uapi
-I.../out/host/usr/mipsel-unknown-linux-uclibc/sysroot/usr/include/glib-2.0
-I.../out/host/usr/mipsel-unknown-linux-uclibc/sysroot/usr/lib/glib-2.0/include
-DNL80211_RECENT_FIELDS -I../libstacktrace -I.../out/host/usr/include
-DCOMPILE_FOR_HOST=1 -o host-http_bouncer.o -c http_bouncer.c

finaltargets.google_platform-HEAD: http_bouncer.c:17:23: fatal error:
                                   curl/curl.h: No such file or directory
finaltargets.google_platform-HEAD:  #include <curl/curl.h>
finaltargets.google_platform-HEAD:                        ^
finaltargets.google_platform-HEAD: compilation terminated.
finaltargets.google_platform-HEAD: make[3]: *** [host-http_bouncer.o] Error 1

Change-Id: I001860c8788de3cf621e89c3c249b5bc20c3f360