buildroot: gcc 5.3 fixes
toolchain/helpers.mk: support for multiple files named ld*-uClibc.so.*
e2fsprogs: use old-style (gcc4) inlining
netperf: update inlining syntax for gcc5
google_dart_vm: suppress 2 unused variable warnings until they can be fixed upstream

build errors without the dart fix:

buildroot+google_dart_vm.sdk+runtime: In file included from runtime/vm/base_isolate.h:9:0,
buildroot+google_dart_vm.sdk+runtime:                  from runtime/vm/allocation.h:9,
buildroot+google_dart_vm.sdk+runtime:                  from runtime/lib/mirrors.h:8,
buildroot+google_dart_vm.sdk+runtime:                  from runtime/lib/mirrors.cc:5:
buildroot+google_dart_vm.sdk+runtime: runtime/vm/globals.h:30:14: error: ‘dart::kPosInfinity’ defined but not used [-Werror=unused-variable]
buildroot+google_dart_vm.sdk+runtime:  const double kPosInfinity = bit_cast<double>(DART_UINT64_C(0x7ff0000000000000));
buildroot+google_dart_vm.sdk+runtime:               ^
buildroot+google_dart_vm.sdk+runtime: runtime/vm/globals.h:31:14: error: ‘dart::kNegInfinity’ defined but not used [-Werror=unused-variable]
buildroot+google_dart_vm.sdk+runtime:  const double kNegInfinity = bit_cast<double>(DART_UINT64_C(0xfff0000000000000));
buildroot+google_dart_vm.sdk+runtime:               ^
buildroot+google_dart_vm.sdk+runtime: cc1plus: all warnings being treated as errors
buildroot+google_dart_vm.sdk+runtime: make[2]: *** [out/ReleaseXMIPS/obj.target/libdart_lib/runtime/lib/mirrors.o] Error 1

Change-Id: Id62d1fbbddb03bc2dfd2bed82dcd71d40aab5ad1